development:
  adapter: postgresql
  database: graffito_development
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: graffito_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: graffito_production
  pool: 5
  timeout: 5000
